<?php

namespace tests\integration\Pim\Bundle\VersioningBundle\Builder;

use Pim\Component\Catalog\Repository\AttributeRepositoryInterface;
use Test\Integration\TestCase;

/**
 * @author    Marie Bochu <marie.bochu@akeneo.com>
 * @copyright 2016 Akeneo SAS (http://www.akeneo.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
class VersionIntegration extends TestCase
{
    /** @var AttributeRepositoryInterface */
    private $attributeRepository;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->attributeRepository = $this->get('pim_catalog.repository.attribute');
    }

    public function testBuildVersionAttribute()
    {
        $attribute = $this->attributeRepository->findOneByIdentifier('a_date');

//        $this->get('pim_versioning.builder.version')->buildVersion()
    }
}
